name = "{{name}}"
version = "0.1.0"

[registry.metadata]
authors = [""]
description = "Description of {{name}}"
license = ""
categories = [""]

[build.dev]
build = "componentize-py -d ./wit --world nor2:heim/nor2-world componentize app -o {{name}}.wasm"
wasm_path = "./{{name}}.wasm"

[build.prod]
build = "componentize-py -d ./wit --world nor2:heim/nor2-world componentize app -o {{name}}.wasm"
wasm_path = "./{{name}}.wasm"
