[[variable]]
key = "timeout"
value = "60"
desc = "Max-execution time in seconds"
optional = false

[[variable]]
key = "allow_parallel"
var_typ = "Bool"
desc = "Allow parallel on a single node, if true we can run X queued jobs at the same time."
optional = false

[[dependency]]
executable = "rustc"
required_version = ">=1.85"
installation_help = "install rust from here: https://www.rust-lang.org/tools/install"

[[dependency]]
executable = "cargo"
installation_help = "install rust from here: https://www.rust-lang.org/tools/install"

[[dependency]]
executable = "rustup"
installation_help = "install rust from here: https://www.rust-lang.org/tools/install"
